/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param lastMessageAt 
 * @param title 
 * @param type 
 */
@Serializable

public data class Conversation (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "lastMessageAt")
    val lastMessageAt: kotlin.String?,

    @SerialName(value = "title")
    val title: kotlin.String?,

    @SerialName(value = "type")
    val type: kotlin.String

) {


}

