/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models

import com.expys.sdk.models.Intake

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param conversationId 
 * @param createdAt 
 * @param id 
 * @param intake 
 * @param offer 
 * @param status 
 */
@Serializable

public data class CreateInterestResponse (

    @SerialName(value = "conversationId")
    val conversationId: kotlin.String?,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "intake")
    val intake: Intake?,

    @SerialName(value = "offer")
    val offer: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String

) {


}

