/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param offer 
 * @param externalUserID 
 * @param interest 
 */
@Serializable

public data class CreateRedemptionRequest (

    @SerialName(value = "offer")
    val offer: kotlin.String,

    @SerialName(value = "externalUserID")
    val externalUserID: kotlin.String? = null,

    @SerialName(value = "interest")
    val interest: kotlin.String? = null

) {


}

