/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param offer 
 * @param adults 
 * @param blackoutDates 
 * @param children 
 * @param contactMethod 
 * @param contactWindow 
 * @param externalUserID 
 * @param occasion 
 * @param phone 
 * @param preferredDates 
 */
@Serializable

public data class CreateInterestRequest (

    @SerialName(value = "offer")
    val offer: kotlin.String,

    @SerialName(value = "adults")
    val adults: kotlin.Int? = null,

    @SerialName(value = "blackoutDates")
    val blackoutDates: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "children")
    val children: kotlin.Int? = null,

    @SerialName(value = "contactMethod")
    val contactMethod: CreateInterestRequest.ContactMethod? = null,

    @SerialName(value = "contactWindow")
    val contactWindow: CreateInterestRequest.ContactWindow? = null,

    @SerialName(value = "externalUserID")
    val externalUserID: kotlin.String? = null,

    @SerialName(value = "occasion")
    val occasion: CreateInterestRequest.Occasion? = null,

    @SerialName(value = "phone")
    val phone: kotlin.String? = null,

    @SerialName(value = "preferredDates")
    val preferredDates: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: APP_CHAT,SMS,EMAIL,PHONE
     */
    @Serializable
    public enum class ContactMethod(public val value: kotlin.String) {
        @SerialName(value = "APP_CHAT") APP_CHAT("APP_CHAT"),
        @SerialName(value = "SMS") SMS("SMS"),
        @SerialName(value = "EMAIL") EMAIL("EMAIL"),
        @SerialName(value = "PHONE") PHONE("PHONE");
    }
    /**
     * 
     *
     * Values: MORNING,AFTERNOON,EVENING,ANYTIME
     */
    @Serializable
    public enum class ContactWindow(public val value: kotlin.String) {
        @SerialName(value = "MORNING") MORNING("MORNING"),
        @SerialName(value = "AFTERNOON") AFTERNOON("AFTERNOON"),
        @SerialName(value = "EVENING") EVENING("EVENING"),
        @SerialName(value = "ANYTIME") ANYTIME("ANYTIME");
    }
    /**
     * 
     *
     * Values: BIRTHDAY,ANNIVERSARY,ENGAGEMENT,WEDDING,GRADUATION,PROMOTION,BUSINESS,OTHER
     */
    @Serializable
    public enum class Occasion(public val value: kotlin.String) {
        @SerialName(value = "BIRTHDAY") BIRTHDAY("BIRTHDAY"),
        @SerialName(value = "ANNIVERSARY") ANNIVERSARY("ANNIVERSARY"),
        @SerialName(value = "ENGAGEMENT") ENGAGEMENT("ENGAGEMENT"),
        @SerialName(value = "WEDDING") WEDDING("WEDDING"),
        @SerialName(value = "GRADUATION") GRADUATION("GRADUATION"),
        @SerialName(value = "PROMOTION") PROMOTION("PROMOTION"),
        @SerialName(value = "BUSINESS") BUSINESS("BUSINESS"),
        @SerialName(value = "OTHER") OTHER("OTHER");
    }

}

