/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param comment 
 * @param rating 
 * @param submittedAt 
 */
@Serializable

public data class Feedback (

    @SerialName(value = "comment")
    val comment: kotlin.String?,

    @SerialName(value = "rating")
    val rating: kotlin.Int,

    @SerialName(value = "submittedAt")
    val submittedAt: kotlin.String

) {


}

