/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models

import com.expys.sdk.models.RedemptionStatusCounts

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param completionRate 
 * @param memberCount 
 * @param pointsMinted 
 * @param pointsSpent 
 * @param redemptions 
 */
@Serializable

public data class GetAnalyticsSummaryResponse (

    @SerialName(value = "completionRate")
    val completionRate: kotlin.Double,

    @SerialName(value = "memberCount")
    val memberCount: kotlin.Double,

    @SerialName(value = "pointsMinted")
    val pointsMinted: kotlin.Double,

    @SerialName(value = "pointsSpent")
    val pointsSpent: kotlin.Double,

    @SerialName(value = "redemptions")
    val redemptions: RedemptionStatusCounts

) {


}

