/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param balance 
 * @param balanceDisplay 
 * @param balanceUSD 
 * @param creditLimit 
 * @param creditLimitUSD 
 * @param lifetimeSpent 
 * @param lifetimeSpentUSD 
 * @param ratePerPoint 
 * @param settlementMode 
 */
@Serializable

public data class GetBalanceResponse (

    @SerialName(value = "balance")
    val balance: kotlin.Int,

    @SerialName(value = "balanceDisplay")
    val balanceDisplay: kotlin.Double,

    @SerialName(value = "balanceUSD")
    val balanceUSD: kotlin.Double,

    @SerialName(value = "creditLimit")
    val creditLimit: kotlin.Int,

    @SerialName(value = "creditLimitUSD")
    val creditLimitUSD: kotlin.Double,

    @SerialName(value = "lifetimeSpent")
    val lifetimeSpent: kotlin.Int,

    @SerialName(value = "lifetimeSpentUSD")
    val lifetimeSpentUSD: kotlin.Double,

    @SerialName(value = "ratePerPoint")
    val ratePerPoint: kotlin.Double,

    @SerialName(value = "settlementMode")
    val settlementMode: GetBalanceResponse.SettlementMode

) {

    /**
     * 
     *
     * Values: MEMBER_WALLET,ORG_POOL
     */
    @Serializable
    public enum class SettlementMode(public val value: kotlin.String) {
        @SerialName(value = "MEMBER_WALLET") MEMBER_WALLET("MEMBER_WALLET"),
        @SerialName(value = "ORG_POOL") ORG_POOL("ORG_POOL");
    }

}

