/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param contentHTML 
 * @param publishedAt 
 * @param renderedHash 
 * @param type 
 * @param version 
 */
@Serializable

public data class GetTermsContentResponse (

    @SerialName(value = "contentHTML")
    val contentHTML: kotlin.String,

    @SerialName(value = "publishedAt")
    val publishedAt: kotlin.String,

    @SerialName(value = "renderedHash")
    val renderedHash: kotlin.String,

    @SerialName(value = "type")
    val type: GetTermsContentResponse.Type,

    @SerialName(value = "version")
    val version: kotlin.String

) {

    /**
     * 
     *
     * Values: TERMS_OF_SERVICE,PRIVACY_POLICY
     */
    @Serializable
    public enum class Type(public val value: kotlin.String) {
        @SerialName(value = "TERMS_OF_SERVICE") TERMS_OF_SERVICE("TERMS_OF_SERVICE"),
        @SerialName(value = "PRIVACY_POLICY") PRIVACY_POLICY("PRIVACY_POLICY");
    }

}

