/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address 
 * @param city 
 * @param countryCode 
 * @param display 
 * @param state 
 * @param venue 
 */
@Serializable

public data class Location (

    @SerialName(value = "address")
    val address: kotlin.String?,

    @SerialName(value = "city")
    val city: kotlin.String?,

    @SerialName(value = "countryCode")
    val countryCode: kotlin.String?,

    @SerialName(value = "display")
    val display: kotlin.String,

    @SerialName(value = "state")
    val state: kotlin.String?,

    @SerialName(value = "venue")
    val venue: kotlin.String?

) {


}

