/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models

import com.expys.sdk.models.RedemptionCounts
import com.expys.sdk.models.Wallet

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param attributes 
 * @param displayName 
 * @param externalUserID 
 * @param redemptionCounts 
 * @param tier 
 * @param wallet 
 */
@Serializable

public data class MemberSummary (

    @SerialName(value = "attributes")
    val attributes: kotlinx.serialization.json.JsonObject?,

    @SerialName(value = "displayName")
    val displayName: kotlin.String?,

    @SerialName(value = "externalUserID")
    val externalUserID: kotlin.String,

    @SerialName(value = "redemptionCounts")
    val redemptionCounts: RedemptionCounts,

    @SerialName(value = "tier")
    val tier: kotlin.String,

    @SerialName(value = "wallet")
    val wallet: Wallet

) {


}

