/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cancellations 
 * @param completions 
 * @param offerId 
 * @param pointsSpent 
 * @param signups 
 */
@Serializable

public data class OfferAnalytics (

    @SerialName(value = "cancellations")
    val cancellations: kotlin.Double,

    @SerialName(value = "completions")
    val completions: kotlin.Double,

    @SerialName(value = "offerId")
    val offerId: kotlin.String,

    @SerialName(value = "pointsSpent")
    val pointsSpent: kotlin.Double,

    @SerialName(value = "signups")
    val signups: kotlin.Double

) {


}

