/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param description 
 * @param expiresAt 
 * @param id 
 * @param images 
 * @param kind 
 * @param pointsPrice 
 * @param shortDescription 
 * @param title 
 * @param type 
 */
@Serializable

public data class Offer (

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "expiresAt")
    val expiresAt: kotlin.String?,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "images")
    val images: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "kind")
    val kind: kotlin.String,

    @SerialName(value = "pointsPrice")
    val pointsPrice: kotlin.Int?,

    @SerialName(value = "shortDescription")
    val shortDescription: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String

) {


}

