/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param awaitingCustomer 
 * @param awaitingVendor 
 * @param canceled 
 * @param completed 
 * @param `open` 
 * @param purchased 
 * @param submitted 
 * @param total 
 */
@Serializable

public data class RedemptionStatusCounts (

    @SerialName(value = "awaiting_customer")
    val awaitingCustomer: kotlin.Double,

    @SerialName(value = "awaiting_vendor")
    val awaitingVendor: kotlin.Double,

    @SerialName(value = "canceled")
    val canceled: kotlin.Double,

    @SerialName(value = "completed")
    val completed: kotlin.Double,

    @SerialName(value = "open")
    val `open`: kotlin.Double,

    @SerialName(value = "purchased")
    val purchased: kotlin.Double,

    @SerialName(value = "submitted")
    val submitted: kotlin.Double,

    @SerialName(value = "total")
    val total: kotlin.Double

) {


}

