/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models

import com.expys.sdk.models.Feedback

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param canceledNote 
 * @param canceledReason 
 * @param conversationId 
 * @param createdAt 
 * @param endAt 
 * @param feedback 
 * @param id 
 * @param offer 
 * @param startAt 
 * @param status 
 */
@Serializable

public data class Redemption (

    @SerialName(value = "canceledNote")
    val canceledNote: kotlin.String?,

    @SerialName(value = "canceledReason")
    val canceledReason: Redemption.CanceledReason?,

    @SerialName(value = "conversationId")
    val conversationId: kotlin.String?,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    @SerialName(value = "endAt")
    val endAt: kotlin.String?,

    @SerialName(value = "feedback")
    val feedback: Feedback?,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "offer")
    val offer: kotlin.String,

    @SerialName(value = "startAt")
    val startAt: kotlin.String?,

    @SerialName(value = "status")
    val status: kotlin.String

) {

    /**
     * 
     *
     * Values: SOLD_OUT,VENDOR_DECLINED,DATE_UNAVAILABLE,MEMBER_REQUESTED,EXPIRED,OTHER
     */
    @Serializable
    public enum class CanceledReason(public val value: kotlin.String) {
        @SerialName(value = "SOLD_OUT") SOLD_OUT("SOLD_OUT"),
        @SerialName(value = "VENDOR_DECLINED") VENDOR_DECLINED("VENDOR_DECLINED"),
        @SerialName(value = "DATE_UNAVAILABLE") DATE_UNAVAILABLE("DATE_UNAVAILABLE"),
        @SerialName(value = "MEMBER_REQUESTED") MEMBER_REQUESTED("MEMBER_REQUESTED"),
        @SerialName(value = "EXPIRED") EXPIRED("EXPIRED"),
        @SerialName(value = "OTHER") OTHER("OTHER");
    }

}

