/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param AWAITING_CUSTOMER 
 * @param AWAITING_VENDOR 
 * @param CANCELED 
 * @param COMPLETED 
 * @param OPEN 
 * @param PURCHASED 
 * @param SUBMITTED 
 */
@Serializable

public data class RedemptionCounts (

    @SerialName(value = "AWAITING_CUSTOMER")
    val AWAITING_CUSTOMER: kotlin.Double,

    @SerialName(value = "AWAITING_VENDOR")
    val AWAITING_VENDOR: kotlin.Double,

    @SerialName(value = "CANCELED")
    val CANCELED: kotlin.Double,

    @SerialName(value = "COMPLETED")
    val COMPLETED: kotlin.Double,

    @SerialName(value = "OPEN")
    val OPEN: kotlin.Double,

    @SerialName(value = "PURCHASED")
    val PURCHASED: kotlin.Double,

    @SerialName(value = "SUBMITTED")
    val SUBMITTED: kotlin.Double

) {


}

