/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param endAt 
 * @param id 
 * @param offer 
 * @param startAt 
 * @param status 
 */
@Serializable

public data class Redemption (

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    @SerialName(value = "endAt")
    val endAt: kotlin.String?,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "offer")
    val offer: kotlin.String,

    @SerialName(value = "startAt")
    val startAt: kotlin.String?,

    @SerialName(value = "status")
    val status: kotlin.String

) {


}

