/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param archived 
 * @param balanceRetained 
 * @param externalUserID 
 */
@Serializable

public data class RemoveMemberResponse (

    @SerialName(value = "archived")
    val archived: kotlin.Boolean,

    @SerialName(value = "balanceRetained")
    val balanceRetained: kotlin.Boolean,

    @SerialName(value = "externalUserID")
    val externalUserID: kotlin.String

) {


}

