/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param endTime 
 * @param pointsMinted 
 * @param pointsSpent 
 * @param signups 
 * @param startTime 
 */
@Serializable

public data class TimeseriesBucket (

    @SerialName(value = "endTime")
    val endTime: kotlin.String,

    @SerialName(value = "pointsMinted")
    val pointsMinted: kotlin.Double,

    @SerialName(value = "pointsSpent")
    val pointsSpent: kotlin.Double,

    @SerialName(value = "signups")
    val signups: kotlin.Double,

    @SerialName(value = "startTime")
    val startTime: kotlin.String

) {


}

