/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param currencyName 
 * @param currencySymbol 
 * @param currencyUnitsPerUSD 
 */
@Serializable

public data class UpdateConfigurationResponse (

    @SerialName(value = "currencyName")
    val currencyName: kotlin.String,

    @SerialName(value = "currencySymbol")
    val currencySymbol: kotlin.String,

    @SerialName(value = "currencyUnitsPerUSD")
    val currencyUnitsPerUSD: kotlin.Double

) {


}

