/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.expys.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param environment 
 * @param events 
 * @param id 
 * @param signingSecret 
 * @param url 
 */
@Serializable

public data class WebhookEndpointWithSecret (

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    @SerialName(value = "environment")
    val environment: WebhookEndpointWithSecret.Environment,

    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "signingSecret")
    val signingSecret: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String

) {

    /**
     * 
     *
     * Values: SANDBOX,LIVE
     */
    @Serializable
    public enum class Environment(public val value: kotlin.String) {
        @SerialName(value = "SANDBOX") SANDBOX("SANDBOX"),
        @SerialName(value = "LIVE") LIVE("LIVE");
    }

}

